// <auto-generated />
namespace task.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class prod_cat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prod_cat));
        
        string IMigrationMetadata.Id
        {
            get { return "202009201446091_prod_cat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
